'use client';

import { useState } from 'react';
import { useExpenses } from '@/context/ExpenseContext';
import { useSubscription } from '@/hooks/useSubscription';
import { Recommendation } from '@/types';
import Card from '@/components/ui/Card';
import EmptyState from '@/components/ui/EmptyState';
import CategoryBadge from '@/components/expenses/CategoryBadge';
import LoadingSpinner from '@/components/ui/LoadingSpinner';
import UpgradePrompt from '@/components/ui/UpgradePrompt';
import Link from 'next/link';

const PRIORITY_STYLES = {
  high: 'bg-red-50 text-red-600 border-red-200',
  medium: 'bg-amber-50 text-amber-600 border-amber-200',
  low: 'bg-emerald-50 text-emerald-600 border-emerald-200',
};

const PRIORITY_ICONS = {
  high: (
    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
    </svg>
  ),
  medium: (
    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  low: (
    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
    </svg>
  ),
};

export default function AIInsightsPage() {
  const { expenses, isHydrated } = useExpenses();
  const { isFree } = useSubscription();
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [period, setPeriod] = useState<string>('all time');

  async function handleAnalyze() {
    setIsLoading(true);
    setError(null);

    let filtered = expenses;
    if (period === 'last month') {
      const oneMonthAgo = new Date();
      oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
      const cutoff = oneMonthAgo.toISOString().slice(0, 10);
      filtered = expenses.filter((e) => e.date >= cutoff);
    } else if (period === 'last week') {
      const oneWeekAgo = new Date();
      oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
      const cutoff = oneWeekAgo.toISOString().slice(0, 10);
      filtered = expenses.filter((e) => e.date >= cutoff);
    }

    if (filtered.length === 0) {
      setError('No expenses found for the selected period.');
      setIsLoading(false);
      return;
    }

    try {
      const res = await fetch('/api/recommendations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ expenses: filtered, period }),
      });
      const data = await res.json();

      if (data.error) {
        setError(data.error);
      } else {
        setRecommendations(data.recommendations || []);
      }
    } catch {
      setError('Failed to generate recommendations. Please try again.');
    }

    setIsLoading(false);
  }

  if (!isHydrated) {
    return (
      <div className="flex items-center justify-center py-20">
        <LoadingSpinner />
      </div>
    );
  }

  if (isFree) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground">AI Insights</h1>
          <p className="text-sm text-muted mt-1">Get personalized spending recommendations</p>
        </div>
        <Card>
          <UpgradePrompt
            feature="AI Insights"
            description="Get personalized spending recommendations, savings opportunities, and smart financial tips powered by AI."
          />
        </Card>
      </div>
    );
  }

  if (expenses.length === 0) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground">AI Insights</h1>
          <p className="text-sm text-muted mt-1">Get personalized spending recommendations</p>
        </div>
        <EmptyState
          title="No expenses to analyze"
          description="Import some expenses first, then come back for AI-powered spending recommendations."
          action={
            <Link href="/import" className="px-6 py-2.5 gradient-bg text-white rounded-xl text-sm font-semibold hover:opacity-90 transition-opacity shadow-md">
              Import Expenses
            </Link>
          }
        />
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold text-foreground">AI Insights</h1>
        <p className="text-sm text-muted mt-1">Get personalized spending recommendations powered by AI</p>
        <p className="text-xs text-muted mt-2 italic">
          These insights are generated by AI and are for informational use only. They do not constitute professional financial, tax, or investment advice.
        </p>
      </div>

      <Card>
        <div className="flex flex-col sm:flex-row sm:items-center gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 gradient-bg rounded-xl flex items-center justify-center shrink-0">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">Analyze Spending</p>
              <p className="text-xs text-muted">{expenses.length} total expenses</p>
            </div>
          </div>
          <div className="flex items-center gap-3 sm:ml-auto">
            <select
              value={period}
              onChange={(e) => setPeriod(e.target.value)}
              className="px-4 py-2.5 border border-border rounded-xl text-sm bg-background dark:bg-gray-800 flex-1 sm:flex-none"
            >
              <option value="all time">All Time</option>
              <option value="last month">Last Month</option>
              <option value="last week">Last Week</option>
            </select>
            <button
              onClick={handleAnalyze}
              disabled={isLoading}
              className="px-5 py-2.5 gradient-bg text-white rounded-xl text-sm font-semibold hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed transition-opacity shadow-sm whitespace-nowrap"
            >
              {isLoading ? (
                <span className="flex items-center gap-2">
                  <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />
                  Analyzing...
                </span>
              ) : (
                'Analyze'
              )}
            </button>
          </div>
        </div>
      </Card>

      {isLoading && (
        <Card>
          <div className="flex flex-col items-center py-12">
            <div className="w-16 h-16 gradient-bg rounded-2xl flex items-center justify-center mb-4 animate-pulse-soft shadow-lg">
              <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <p className="text-sm font-medium text-foreground mb-1">AI is analyzing your spending...</p>
            <p className="text-xs text-muted">This may take a few seconds</p>
          </div>
        </Card>
      )}

      {error && (
        <div className="flex items-center gap-3 px-5 py-4 rounded-2xl bg-danger-light border border-red-200 text-sm">
          <svg className="w-5 h-5 text-danger shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <p className="text-danger font-medium">{error}</p>
        </div>
      )}

      {recommendations.length > 0 && (
        <div className="space-y-4">
          {recommendations.map((rec, i) => (
            <Card key={rec.id} className="animate-slide-up">
              <div style={{ animationDelay: `${i * 0.08}s`, animationFillMode: 'backwards' }} className="animate-slide-up">
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-2.5 flex-wrap">
                      <h3 className="font-semibold text-foreground">{rec.title}</h3>
                      <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-lg text-xs font-semibold border ${PRIORITY_STYLES[rec.priority]}`}>
                        {PRIORITY_ICONS[rec.priority]}
                        {rec.priority}
                      </span>
                      {rec.category && <CategoryBadge category={rec.category} />}
                    </div>
                    <p className="text-sm text-muted leading-relaxed">{rec.description}</p>
                  </div>
                  {rec.potentialSavings && (
                    <div className="sm:text-right shrink-0 bg-success-light px-4 py-3 rounded-xl">
                      <p className="text-xs text-muted font-medium mb-0.5">Potential savings</p>
                      <p className="text-xl font-bold text-success">{rec.potentialSavings}</p>
                    </div>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
